CREATE TABLE D_DATE (
    PK_DATE DATE NOT NULL,
    CONSTRAINT PK_DATE PRIMARY KEY (PK_DATE)
);

CREATE TABLE D_TYPE (
    PK_TYPE VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_TYPE PRIMARY KEY (PK_TYPE)
);

CREATE TABLE D_CATEGORIE (
    PK_CATEGORIE VARCHAR2(90) NOT NULL,
    CATEGORIE VARCHAR2(40) NOT NULL,
    SOUS_CATEGORIE VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (PK_CATEGORIE)
);

CREATE TABLE D_OPERATION (
    PK_CODE VARCHAR2(40) NOT NULL,
    LABEL VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_CODE PRIMARY KEY (PK_CODE)
);

CREATE TABLE F_TRANSACTION (
    PK_REFERENCE VARCHAR2(200) NOT NULL,
    FK_DATE DATE NOT NULL,
    FK_TYPE VARCHAR2(40) NOT NULL,
    FK_CATEGORIE VARCHAR2(90) NOT NULL,
    FK_CODE VARCHAR2(40) NOT NULL,
    MONTANT NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_TRANSACTION PRIMARY KEY (PK_REFERENCE),
    CONSTRAINT FK_DATE FOREIGN KEY (FK_DATE) REFERENCES D_DATE(PK_DATE),
    CONSTRAINT FK_TYPE FOREIGN KEY (FK_TYPE) REFERENCES D_TYPE(PK_TYPE),
    CONSTRAINT FK_CATEGORIE FOREIGN KEY (FK_CATEGORIE) REFERENCES D_CATEGORIE(PK_CATEGORIE),
    CONSTRAINT FK_CODE FOREIGN KEY (FK_CODE) REFERENCES D_OPERATION(PK_CODE)
);

-- ALTER TABLE D_OPERATION
-- MODIFY LABEL VARCHAR2(50);

--? DROP
-- DROP TABLE D_DATE;
-- DROP TABLE D_TYPE;
-- DROP TABLE D_CATEGORIE;
-- DROP TABLE D_OPERATION;
-- DROP TABLE F_TRANSACTION;

--? SELECT
-- SELECT * FROM ODS_TRANSACTION;
-- SELECT * FROM DWH_TRANSACTION;

-- SELECT * FROM D_DATE;
-- SELECT * FROM D_OPERATION;
-- SELECT * FROM D_CATEGORIE;
-- SELECT * FROM D_CREDIT_DEBIT;
-- SELECT * FROM F_TRANSACTION;
