CREATE TABLE D_DATE (
    PK_DATE DATE NOT NULL,
    CONSTRAINT PK_DATE PRIMARY KEY (PK_DATE)
);

CREATE TABLE D_OPERATION (
    PK_TYPE VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_TYPE PRIMARY KEY (PK_TYPE)
);

CREATE TABLE D_CATEGORIE (
    PK_CATEGORIE VARCHAR2(40) NOT NULL,
    PK_SOUS_CATEGORIE VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (PK_CATEGORIE, PK_SOUS_CATEGORIE)
);

CREATE TABLE D_CREDIT_DEBIT (
    PK_LABEL CHAR(1) NOT NULL,
    CONSTRAINT PK_LABEL PRIMARY KEY (PK_LABEL)
);

CREATE TABLE F_TRANSACTION (
    PK_REFERENCE VARCHAR2(200) NOT NULL,
    PK_DATE DATE NOT NULL,
    PK_TYPE VARCHAR2(40) NOT NULL,
    PK_CATEGORIE VARCHAR2(40) NOT NULL,
    PK_SOUS_CATEGORIE VARCHAR2(40) NOT NULL,
    PK_LABEL CHAR(1) NOT NULL,
    MONTANT NUMBER NOT NULL,
    CONSTRAINT PK_TRANSACTION PRIMARY KEY (PK_REFERENCE),
    CONSTRAINT FK_DATE FOREIGN KEY (PK_DATE) REFERENCES D_DATE(PK_DATE),
    CONSTRAINT FK_TYPE FOREIGN KEY (PK_TYPE) REFERENCES D_OPERATION(PK_TYPE),
    CONSTRAINT FK_CATEGORIE FOREIGN KEY (PK_CATEGORIE, PK_SOUS_CATEGORIE) REFERENCES D_CATEGORIE(PK_CATEGORIE, PK_SOUS_CATEGORIE),
    CONSTRAINT FK_LABEL FOREIGN KEY (PK_LABEL) REFERENCES D_CREDIT_DEBIT(PK_LABEL)
);



--? DROP
-- DROP TABLE D_DATE;
-- DROP TABLE D_OPERATION;
-- DROP TABLE D_CATEGORIE;
-- DROP TABLE D_CREDIT_DEBIT;
-- DROP TABLE F_TRANSACTION;

--? SELECT
-- SELECT * FROM ODS_TRANSACTION;
-- SELECT * FROM DWH_TRANSACTION;

-- SELECT * FROM D_DATE;
-- SELECT * FROM D_OPERATION;
-- SELECT * FROM D_CATEGORIE;
-- SELECT * FROM D_CREDIT_DEBIT;
-- SELECT * FROM F_TRANSACTION;
